### ISSUE TITLE
Anonymous access to /bin/browser.html results in a 403 page

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum#180]
When accessing the Composum Browser without being logged in a 403 page is returned. It would be more user-friendly if a login form would be presented, when needed.

According to the [Sling Authenticator documentation](https://sling.apache.org/documentation/the-sling-engine/authentication/authentication-framework.html#anonymous-login) it should be possible for composum to indicate that certain URLs must have authentication by adding a registration property of `sling.auth.requirements=/bin/browser.html` to any service.

**Comment by stoerr** [comment]
Thank you! I had to extend the PR a little, since this problem also creates trouble if the user switches between the various internal views in the browser. We didn't notice that, since we usually have Composum Platform deployed, too, which configures everything below /bin to authenticated, anyway. :-)

@ist-rw What do you think, Ralf?
