### ISSUE TITLE
Release w/ Groovy 3 Support

### ISSUE THREAD

**Issue by klcodanr** [ist-dresden/composum#200]
Hi would it be possible to release Composum Nodes with Groovy Lang 3 support?

**Comment by stoerr** [comment]
Did you try that and had any problems? I tried that recently and it worked. I did have to restart the server, though. Of course, you need to install groovy first. Some hints on that:


To use the groovy support of Sling, it is necessary to install the groovy OSGI bundle. The bundle is available in the maven repository, and can be downloaded e.g. with

mvn dependency:copy -Dartifact=org.codehaus.groovy:groovy:3.0.4 -DoutputDirectory=.

and installed via the console. This bundle contains the basic language - possibly you need to install some additional groovy modules.

To use the groovy execution in the browser the server needs to be restarted, or at least the composum core commons bundle.

**Comment by stoerr** [comment]
I'm closing that since there was no response.

**Comment by klcodanr** [comment]
Sorry, I missed the notification. I have validated that the Groovy 3 support works, however, the released version 1.12.1 does not support Groovy 3.

**Comment by stoerr** [comment]
For the record, since I had to look it up again: to get Groovy 3 running one needs to install

mvn dependency:copy -Dartifact=org.codehaus.groovy:groovy:3.0.19 -DoutputDirectory=.
mvn dependency:copy -Dartifact=org.codehaus.groovy:groovy-json:3.0.19 -DoutputDirectory=.
mvn dependency:copy -Dartifact=org.codehaus.groovy:groovy-templates:3.0.19 -DoutputDirectory=.
mvn dependency:copy -Dartifact=org.apache.sling:org.apache.sling.scripting.groovy:1.2.0 -DoutputDirectory=.

scripting.groovy 1.3.0 requires groovy 4.
