### ISSUE TITLE
User management with Sling 7

### ISSUE THREAD

**Issue by glucazeau** [ist-dresden/composum#42]
Hello,

I've started a Sling 7 standalone jar and deployed the following bundles:

com.composum.core.usermgnt - 1.4.0
com.composum.core.jslibs - 1.4.0
com.composum.core.console - 1.4.0
com.composum.core.commons - 1.4.0

But when I try to access the user management page, I get this error:

> GET /dev/bin/core/usermanagement.tree.json/ HTTP/1.1] ERROR c.c.s.c.servlet.ServletOperationSet - null
> javax.jcr.UnsupportedRepositoryOperationException: null
>   at org.apache.jackrabbit.core.security.user.UserManagerImpl.getPath(UserManagerImpl.java:849)
>   at org.apache.jackrabbit.core.security.user.AuthorizableImpl.getPath(AuthorizableImpl.java:281)
>   at org.apache.jackrabbit.core.security.user.UserImpl.getPath(UserImpl.java:37)

I have the same error with version 1.5.0 of the bundles.

Do I have to upgrade some bundles to be able to use this feature with Sling 7 ?

Thank you for your help

**Comment by glucazeau** [comment]
Is there a chance it would work with Sling 7, or it requires Oak ? I've upgraded every jackrabbit bundle I could to the same version used in Sling 8, but still the same error.

**Comment by mzeibig** [comment]
This is because we use UserManager API methods not supported in Sling 7.
All method based on the path of a user or group throw an `UnsupportedRepositoryOperationException`. Most of this usages could be changed from path to id. But this requires some work to be done. It is not planned at the moment but I will keep it in mind.
